/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BadgeResponseDto struct {
	// バッジの識別子
	Id string `json:"id"`
	// バッジのラベル名
	Label string `json:"label"`
	// バッジのファイル名
	Filename string `json:"filename"`
	// バッジの作成目的や用途など任意で設定可能な説明文
	Description string `json:"description"`
	// バッジの状態(1: 利用可, 0: 利用停止中)
	Status float64 `json:"status"`
	// バッジに紐付いたVCスキーマの配列
	VcSchema *AllOfBadgeResponseDtoVcSchema `json:"vcSchema"`
	// バッジに紐付いたVC情報の配列
	VcInfo *AllOfBadgeResponseDtoVcInfo `json:"vcInfo"`
	// バッジの作成日時
	CreatedAt string `json:"createdAt"`
	// バッジの最終更新日時
	UpdatedAt string `json:"updatedAt"`
}
