/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// バッジに紐付いたVCスキーマの配列
type AllOfBadgeResponseDtoVcSchema struct {
	// (必須) VCスキーマの識別子
	Id string `json:"id"`
	// (必須) VCスキーマのタイトル
	Title string `json:"title"`
	// (必須) VCスキーマのバージョン
	Version string `json:"version"`
	// (任意) VCスキーマの説明文
	Description string `json:"description"`
	// (必須) VCスキーマがバッジのスキーマか否か
	IsBadgeSchema string `json:"isBadgeSchema,omitempty"`
	// (任意) このVCスキーマを用いて生成したVC情報の配列。
	VcInfos []VcInfo `json:"vcInfos,omitempty"`
	// (任意) VCスキーマに設定したcontext項目の配列
	VcContexts []VcContext `json:"vcContexts,omitempty"`
	// (必須) VCスキーマの項目情報の配列
	VcSchemaProperties []VcSchemaProperty `json:"vcSchemaProperties,omitempty"`
	// (任意) VCスキーマを紐付けたグループの配列
	Groups []Group `json:"groups,omitempty"`
	// (任意) VCスキーマを紐付けたバッジ
	Badges []Badge `json:"badges,omitempty"`
	// (任意) VCスキーマに紐付けるバッジ用の画像。`isBadgeSchema`プロパティが`true`の場合必須。
	File *Object `json:"file,omitempty"`
	// (必須) VCスキーマを作成したユーザーアカウント。
	CreatedBy *Object `json:"createdBy"`
	// (必須) VCスキーマの作成日時
	CreatedAt string `json:"createdAt"`
	// (必須) VCスキーマの更新日時
	UpdatedAt string `json:"updatedAt"`
}
