/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// (任意) 検証を実行したVP情報の識別子
type AllOfVerificationVpInfo struct {
	// (必須) VP情報の識別子
	Id string `json:"id"`
	// (任意) VPの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ
	Label string `json:"label,omitempty"`
	// (必須) VPのハッシュ値。VPの保管における識別子として用いる。
	Hash string `json:"hash,omitempty"`
	// (任意) VCの発行目的や用途など任意で設定可能な説明文。
	Description string `json:"description,omitempty"`
	// (必須) VPのバイナリデータ
	Raw string `json:"raw"`
	// (任意) VP情報を生成したユーザーアカウント
	CreatedBy *Object `json:"createdBy"`
	// (任意) VP情報と紐付いたアカウント
	User *Object `json:"user,omitempty"`
	// (任意) VPを生成する元となるVC情報
	VcInfos []VcInfo `json:"vcInfos,omitempty"`
	// (任意) VP情報に紐づいたグループの配列
	Groups []Group `json:"groups,omitempty"`
	// (任意) VP生成時の署名に用いるDID情報の識別子
	DidInfo *Object `json:"didInfo,omitempty"`
	// (任意) VPの検証結果
	Verifications []Verification `json:"verifications,omitempty"`
	// (必須) VP情報の作成日時
	CreatedAt string `json:"createdAt"`
	// (必須) VP情報の更新日時
	UpdatedAt string `json:"updatedAt"`
}
