/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateVcSchemaDto struct {
	// (必須) 新規生成するVCスキーマのタイトル
	Title string `json:"title"`
	// (必須) VCスキーマのバージョン(デフォルト: 1.0.0)
	Version string `json:"version"`
	// (任意) VCスキーマに設定する@context文字列の配列
	Contexts []string `json:"contexts,omitempty"`
	// (任意) VCスキーマの説明文
	Description string `json:"description,omitempty"`
	// (任意) このスキーマがバッジのスキーマか否か(デフォルト: false)
	IsBadgeSchema bool `json:"isBadgeSchema"`
	// (任意) バッジの画像のファイル識別子。'`isBadgeSchema`プロパティが`true`であり、バッジスキーマとして利用する場合は必須のパラメータ。
	FileId string `json:"fileId"`
	// (必須) VCのスキーマの各項目における項目名と項目型のオブジェクトの配列
	PropArray []VcSchemaProperty `json:"propArray"`
}
