/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VcSchemaProperty struct {
	// The ID of the vcSchema
	Id string `json:"id"`
	// property Index number
	PropIndex float64 `json:"propIndex"`
	// property Name of credentialSubject
	PropName string `json:"propName"`
	// property Type of credentialSubject
	PropType string `json:"propType"`
	// parent property
	ParentObjectIndex float64 `json:"parentObjectIndex"`
	// The VcSchema is origin
	VcSchema *AllOfVcSchemaPropertyVcSchema `json:"vcSchema,omitempty"`
	// The date the user was created
	CreatedAt string `json:"createdAt"`
	// The date the user was last updated
	UpdatedAt string `json:"updatedAt"`
}
