/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Mail struct {
	// (必須) 送信済みメールの識別子
	Id string `json:"id"`
	// (必須) 送信済みメールの件名
	Title string `json:"title"`
	// (必須) 送信済みメールの内容
	Content string `json:"content"`
	// (必須) 全てのuser権限アカウントに対して送信するか。(true: 全てのuser権限アカウントに送信, false: 全てのuser権限アカウントに送信しない)
	ForEveryUser bool `json:"forEveryUser"`
	// (必須) 全てのclient権限アカウントに対して送信するか。(true: 全てのclient権限アカウントに送信, false: 全てのclient権限アカウントに送信しない)
	ForEveryClient bool `json:"forEveryClient"`
	// (任意) メールの送信先となるユーザーアカウントの配列
	Users []User `json:"users,omitempty"`
	// (任意) メールの送信先となるグループの配列
	Groups []Group `json:"groups,omitempty"`
	// (必須) メール送信操作を行ったAdmin権限アカウント
	CreatedBy []User `json:"createdBy,omitempty"`
	// (必須) メールの送信日時
	CreatedAt string `json:"createdAt"`
	// (必須) メールの送信日時
	UpdatedAt string `json:"updatedAt"`
}
