/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Group struct {
	// (必須) グループの識別子
	Id string `json:"id"`
	// (必須) グループの名前。(例: プロジェクト名や企業名など)
	Name string `json:"name"`
	// (必須) グループの状態(1: アクティブ, 0: 停止中)
	Status string `json:"status"`
	// (任意) グループの作成目的や用途など任意で設定可能な説明文
	Description string `json:"description"`
	// (任意) グループに紐付いたアカウントの配列
	Users []User `json:"users,omitempty"`
	// (必須) グループを作成したユーザーアカウント。
	CreatedBy *AllOfGroupCreatedBy `json:"createdBy"`
	// (任意) グループに紐付いたDID情報の配列
	DidInfos []DidInfo `json:"didInfos,omitempty"`
	// (任意) グループに紐付いたVC情報の配列
	VcInfos []VcInfo `json:"vcInfos,omitempty"`
	// (任意) グループに紐付いたVP情報の配列
	VpInfos []VpInfo `json:"vpInfos,omitempty"`
	// (任意) グループに紐付いたVCスキーマの配列
	VcSchemas []VcSchema `json:"vcSchemas,omitempty"`
	// (必須) グループの作成日時
	CreatedAt string `json:"createdAt"`
	// (必須) グループの最終更新日時
	UpdatedAt string `json:"updatedAt"`
}
