/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// (任意) VP生成時の署名に用いるDID情報の識別子
type AllOfVpInfoDidInfo struct {
	// (必須) DID情報の識別子
	Id string `json:"id"`
	// (必須) DID情報の管理に用いるユニークな識別子
	ManageUuid string `json:"manageUuid"`
	// (必須) DID
	Did string `json:"did"`
	// (必須) DIDメソッド
	Method string `json:"method"`
	// (任意) DIDの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: did-for-project1)
	Label string `json:"label"`
	// (任意) did:webメソッドでDIDを生成する際に必要なドメイン名。DIDによって指定されたドメインがドメインネームシステム(DNS)を通じて解決されるときのホスト名。did:webメソッド以外では必要のないカラムである。
	DomainName string `json:"domainName"`
	// (必須) DID情報に紐付いた秘密鍵を本アプリケーションで保管しているか否か
	ExistPrivateKey bool `json:"existPrivateKey"`
	// (任意) DID情報の生成目的や用途など任意で設定可能な説明文
	Description string `json:"description"`
	// (任意) DID情報に紐付いたアカウントの配列
	User *Object `json:"user,omitempty"`
	// (任意) DIDを生成したユーザーアカウント
	CreatedBy *Object `json:"createdBy"`
	// (任意) 生成時に署名にDIDを用いたVP情報
	VpInfos *Object `json:"vpInfos,omitempty"`
	// (任意) DID情報に紐づいたグループの配列
	Groups []Group `json:"groups,omitempty"`
	// (必須) DID情報の作成日時
	CreatedAt string `json:"createdAt"`
	// (必須) DID情報の最終更新
	UpdatedAt string `json:"updatedAt"`
}
