/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// (任意) VC情報と紐付いたバッジ
type AllOfVcInfoBadge struct {
	// (必須) バッジの識別子
	Id string `json:"id"`
	// (任意) バッジのラベル名
	Label string `json:"label,omitempty"`
	// (任意) バッジのファイル名
	Filename string `json:"filename,omitempty"`
	// (任意) バッジの作成目的や用途など任意で設定可能な説明文
	Description string `json:"description"`
	// (必須) バッジの状態(1: アクティブ, 0: 停止中)
	Status float64 `json:"status"`
	// (任意) バッジに紐付いたVCスキーマ
	VcSchema *Object `json:"vcSchema,omitempty"`
	// (任意) バッジに紐付き、メタデータとなるVC情報
	VcInfo *Object `json:"vcInfo,omitempty"`
	// (必須) グループの作成日時
	CreatedAt string `json:"createdAt"`
	// (必須) グループの最終更新日時
	UpdatedAt string `json:"updatedAt"`
}
