/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserResponseDto struct {
	// ユーザーアカウントの識別子
	Id string `json:"id"`
	// ユーザーアカウントの名前
	Name string `json:"name"`
	// ユーザーアカウントのメールアドレス
	Email string `json:"email"`
	// ユーザーアクティベーション(true: アクティブ /false: 停止中)
	NeedActivateFlow bool `json:"needActivateFlow"`
	// ユーザーのアカウントステータス(\"inactive\": アクティブ未完了, \"acrivating\": アクティブ作業途中, \"active\": アクティブ中, \"deactive\": 論理削除済)
	Status string `json:"status"`
	// ユーザーのアカウントロール(\"admin\", \"user\", \"client\")
	Role string `json:"role"`
	// (任意) ユーザーアカウントがアップロードしたファイルの配列。
	UserTokens []UserToken `json:"userTokens"`
	// ユーザーアカウントを作成したユーザーアカウント
	CreatedBy *AllOfUserResponseDtoCreatedBy `json:"createdBy"`
	// ユーザーアカウントに紐付けられたDID情報の配列
	DidInfos []DidInfo `json:"didInfos,omitempty"`
	// ユーザーアカウントに紐付けられたVC情報の配列
	VcInfos []VcInfo `json:"vcInfos,omitempty"`
	// ユーザーアカウントに紐付けられたVP情報の配列
	VpInfos []VpInfo `json:"vpInfos,omitempty"`
	// ユーザーアカウントが作成したグループの配列
	Groups []Group `json:"groups,omitempty"`
	// ユーザーアカウントに紐付けされたVP情報の配列
	CreatedUsers []User `json:"createdUsers,omitempty"`
	// ユーザーが作成したVC情報の配列
	CreatedVcInfos []VcInfo `json:"createdVcInfos,omitempty"`
	// ユーザーが作成したVP情報の配列
	CreatedVpInfos []VpInfo `json:"createdVpInfos,omitempty"`
	// ユーザーアカウントが作成したグループの配列
	CreatedGroups []Group `json:"createdGroups,omitempty"`
	// ユーザーが作成したDID情報の配列
	CreatedDidInfos []DidInfo `json:"createdDidInfos,omitempty"`
	// ユーザーが作成したVCスキーマの配列
	CreatedVcSchemas []VcSchema `json:"createdVcSchemas,omitempty"`
	// ユーザーアカウントが実行した検証結果の配列
	CreatedVerifications []Verification `json:"createdVerifications,omitempty"`
	// Admin権限アカウントが送信したメールの配列
	CreatedMails []Mail `json:"createdMails,omitempty"`
	// ユーザーアカウントに紐付けされたファイルの配列
	CreatedFiles []*os.File `json:"createdFiles,omitempty"`
	// ユーザーアカウントの作成日時
	CreatedAt string `json:"createdAt"`
	// ユーザーアカウントの更新日時
	UpdatedAt string `json:"updatedAt"`
}
