/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Verification struct {
	// (必須) 検証結果の識別子
	Id string `json:"id"`
	// (必須) 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
	Label string `json:"label"`
	// (必須) VC/VPの検証結果(true: 検証に成功, false: 検証に失敗)
	Result bool `json:"result"`
	// (任意) 検証結果を作成したユーザーアカウント
	CreatedBy *AllOfVerificationCreatedBy `json:"createdBy"`
	// (任意) 検証を実行したVC情報の識別子
	VcInfo *AllOfVerificationVcInfo `json:"vcInfo,omitempty"`
	// (任意) 検証を実行したVP情報の識別子
	VpInfo *AllOfVerificationVpInfo `json:"vpInfo,omitempty"`
	// (必須) 検証実行時の日時
	CreatedAt string `json:"createdAt"`
	// (必須) 検証結果の最終更新日
	UpdatedAt string `json:"updatedAt"`
}
