/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 本アプリケーションにおけるVCの管理情報
type AllOfVcInfoResponseDtoVcInfo struct {
	// (必須) VC情報の識別子
	Id string `json:"id"`
	// (任意) VCの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: vc-for-project1)
	Label string `json:"label"`
	// (必須) VCのハッシュ値。VCの保管における識別子として用いる。
	Hash string `json:"hash"`
	// (任意) VCの発行目的や用途など任意で設定可能な説明文。
	Description string `json:"description"`
	// (任意) VC情報を生成したユーザーアカウント
	CreatedBy *Object `json:"createdBy"`
	// (任意) 発行したVCの元となるVCスキーマ
	VcSchema *Object `json:"vcSchema,omitempty"`
	// (任意) VC情報と紐付いたアカウント
	User *Object `json:"user,omitempty"`
	// (任意) このVCを元に生成したVP情報の配列
	VpInfos []VpInfo `json:"vpInfos,omitempty"`
	// (任意) VC情報に紐づいたグループの配列
	Groups []Group `json:"groups,omitempty"`
	// (任意) VC情報と紐付いたバッジ
	Badge *Object `json:"badge,omitempty"`
	// (任意) このVCの検証結果の配列。
	Verifications []Verification `json:"verifications,omitempty"`
	// (必須) VC情報の作成日時
	CreatedAt string `json:"createdAt"`
	// (必須) VC情報の更新日時
	UpdatedAt string `json:"updatedAt"`
}
