/*
 * iDroit Dashboard Admin API
 *
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * API version: 0.9.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// (任意) DIDを生成したユーザーアカウント
type AllOfDidInfoCreatedBy struct {
	// アカウントの識別子
	Id string `json:"id"`
	// アカウントの名前
	Name string `json:"name"`
	// アカウントのメールアドレス
	Email string `json:"email"`
	// アカウントのパスワード(8文字以上20字未満)
	Password string `json:"password"`
	// (必須: {default: false}) アカウントの有効化フローが必要か否か(true: 必要 /false: 不要)
	NeedActivateFlow bool `json:"needActivateFlow"`
	// ユーザーのアカウントステータス
	Status string `json:"status"`
	// アカウントのロール(admin/user/clinet)
	Role string `json:"role"`
	// (任意) このアカウントを作成したユーザー
	CreatedBy *Object `json:"createdBy,omitempty"`
	// (任意) アカウントに紐付けされたDID情報の配列
	DidInfos []DidInfo `json:"didInfos,omitempty"`
	// (任意) アカウントに紐付けされたVC情報の配列
	VcInfos []VcInfo `json:"vcInfos,omitempty"`
	// (任意) アカウントに紐付けされたVP情報の配列
	VpInfos []VpInfo `json:"vpInfos,omitempty"`
	// (任意) アカウントに紐付けされたグループの配列
	Groups []Group `json:"groups,omitempty"`
	// (任意) ユーザーアカウントがアップロードしたファイルの配列。
	UserTokens []UserToken `json:"userTokens"`
	// (任意) このユーザーによって作成されたアカウントの配列
	CreatedUsers []User `json:"createdUsers,omitempty"`
	// (任意) アカウントに紐付けされたVC情報の配列
	CreatedVcInfos []VcInfo `json:"createdVcInfos,omitempty"`
	// (任意) アカウントに紐付けされたVP情報の配列
	CreatedVpInfos []VpInfo `json:"createdVpInfos,omitempty"`
	// (任意) アカウントに作成したグループの配列
	CreatedGroups []Group `json:"createdGroups,omitempty"`
	// (任意) アカウントが作成したDID情報の配列
	CreatedDidInfos []DidInfo `json:"createdDidInfos,omitempty"`
	// (任意) ユーザーアカウントが作成したVCスキーマの配列。
	CreatedVcSchemas []VcSchema `json:"createdVcSchemas"`
	// (任意) ユーザーアカウントが実行した検証結果の配列。
	CreatedVerifications []Verification `json:"createdVerifications"`
	// (任意) Admin権限アカウントが送信したメールの配列(Adminロール以外の場合、関係のないカラム)
	CreatedMails []Mail `json:"createdMails,omitempty"`
	// (任意) ユーザーアカウントがアップロードしたファイルの配列。
	CreatedFiles []*os.File `json:"createdFiles"`
	// ユーザーアカウントの作成日時
	CreatedAt string `json:"createdAt"`
	// ユーザーアカウントの更新日時
	UpdatedAt string `json:"updatedAt"`
}
